/*
 * BSD Zero Clause License
 *
 * Copyright (c) 2026-2026 zodac.net
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
 * SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
 * IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

package net.zodac.diurnal.note;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import net.zodac.diurnal.note.crypto.Aes256Gcm;
import net.zodac.diurnal.note.crypto.DataKeyEnvelope;
import net.zodac.diurnal.note.crypto.MasterKey;
import net.zodac.diurnal.user.User;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * The single owner of a user's notes data key: minting one when their account is created, and opening it on the requests that read or write a note.
 *
 * <p>
 * The key is generated by the application and never involves the user — it is not shown to them, cannot be chosen or changed by them, and nothing
 * about it appears in the interface. What protects it is {@code NOTE_ENCRYPTION_KEY}, which lives in configuration rather than in the database, so
 * the sealed notes and the wrapped keys are together useless to anyone holding only a dump, a backup or a replica.
 *
 * <p>
 * <strong>An administrator with the running server has both</strong>, and can therefore read notes. That is the deliberate limit of this design: it
 * defends against losing the database, not against the operator. Anything stronger requires the user to hold a secret, which was tried and removed.
 *
 * <p>
 * <strong>A data key must never reach the application log</strong>, on the same terms as a note's content itself (see {@link NoteService}) and more
 * strictly still — a leaked note exposes one day, a leaked data key exposes every day at once. Every statement here logs the account and no more.
 *
 * <p>
 * Callers own the transaction; the minting methods assume one is already active.
 */
@ApplicationScoped
public class NoteKeys {

    private static final Logger LOGGER = LogManager.getLogger(NoteKeys.class);

    private final NotesEncryptionConfig notesEncryptionConfig;

    /**
     * Injects the configured master key that every user's data key is wrapped with.
     *
     * @param notesEncryptionConfig the notes encryption settings
     */
    @Inject
    public NoteKeys(final NotesEncryptionConfig notesEncryptionConfig) {
        this.notesEncryptionConfig = notesEncryptionConfig;
    }

    /**
     * Mints a data key for a newly-created account and stores it wrapped.
     *
     * <p>
     * Called from every path that creates a user — local registration and OIDC provisioning alike — so an account has somewhere to put a note from
     * the moment it exists, and no part of the application ever has to handle the "user without a key" case as a live state.
     *
     * @param userId the account to mint a key for
     */
    public void assignTo(final UUID userId) {
        mint(userId);
    }

    /**
     * Opens the user's data key, or reports empty when there is none.
     *
     * <p>
     * An empty result means the account has no key, which is only possible for one created before this feature existed: {@code V28} created
     * {@code user_notes_keys} without backfilling it, and no migration since adds a row. <strong>Such an account provably has no notes</strong> —
     * the same migration emptied the table — so "no key" and "no notes" are the same state, and every account created since has had a key minted
     * with it ({@code NotesKeyAssignmentTest} fails any new user-creation path that does not).
     *
     * <p>
     * <strong>An account holding notes with no key is therefore not a legacy account - it is data loss</strong>, and the only thing that can produce
     * it is something outside this application (a partial restore, a hand-run delete; the row is a {@code PRIMARY KEY ... ON DELETE CASCADE}, so
     * removing the account takes the notes with it). It is logged here rather than answered with an empty journal, because the alternative is a
     * user's whole history vanishing from the interface with nothing said anywhere - beside calendar markers that still show, since those are
     * computed from dates and never touch content. The count costs a query only on the path where the key is already missing.
     *
     * <p>
     * A key that exists but does not open is a different fault - a mismatched {@code NOTE_ENCRYPTION_KEY} - and is logged by {@link #open}.
     *
     * @param userId the owning user
     * @return the data key, or empty when the account has none or it cannot be opened
     */
    Optional<byte[]> forUser(final UUID userId) {
        final UserNotesKey stored = UserNotesKey.findForUser(userId);
        if (stored != null) {
            return open(stored);
        }

        final long noteCount = Note.countForUser(userId);
        if (noteCount > 0L) {
            // The account by email, never its id, and a COUNT rather than anything from a note. See the class Javadoc.
            final String email = emailOf(userId);
            LOGGER.error("Account {} holds {} note(s) but has no notes data key - their journal cannot be read. This is data loss rather than a "
                + "configuration fault: restore that account's user_notes_keys row from a backup.", email, noteCount);
        }
        return Optional.empty();
    }

    /**
     * Opens the user's data key, minting one first if the account has none. Used by the write path, which is transactional and must always end with a
     * key — an account created before this feature existed gets one the first time it writes a note.
     *
     * @param userId the owning user
     * @return the data key, or empty when an existing key cannot be opened
     */
    Optional<byte[]> forUserCreatingIfAbsent(final UUID userId) {
        final UserNotesKey existing = UserNotesKey.findForUser(userId);
        if (existing != null) {
            return open(existing);
        }

        // Minting is correct for exactly one population - an account predating V28, which that migration guarantees holds no notes (see forUser).
        // An account that HAS notes and no key is data loss, and minting over it is what turns a recoverable incident (restore the row, every note
        // opens again) into a permanent one, silently: the new key is well-formed, unwraps perfectly, and opens not one existing note. The count
        // costs a query only here, where the key is already missing, so no ordinary save pays for it.
        final long noteCount = Note.countForUser(userId);
        if (noteCount > 0L) {
            throw new IllegalStateException("Account " + emailOf(userId) + " holds " + noteCount + " note(s) but has no notes data key - refusing "
                + "to mint a replacement, which would leave those notes permanently unreadable. Restore that account's user_notes_keys row.");
        }
        return open(mint(userId));
    }

    /**
     * Brings every stored data key onto the current master key, and reports what could not be brought.
     *
     * <p>
     * This does two jobs that are really one question — "does the configured key fit the data?" — and it is the check that turns this feature's worst
     * failure into a refusal to start. A rotated or mistyped {@code NOTE_ENCRYPTION_KEY} is still well-formed, so the format check passes; it then
     * opens nothing, and every note vanishes from every screen while the rows sit untouched. The calendar's day markers still show, because they are
     * computed from dates and never touch content, so a user would see markers saying they wrote something beside an empty box, with nothing logged.
     *
     * <p>
     * <strong>Rotation.</strong> When previous keys are configured, every row that no longer opens under the current key is opened with one of them,
     * re-wrapped under the current key and its {@code key_version} bumped. That is the whole rotation mechanism: set the new key, keep the old one in
     * {@code NOTE_ENCRYPTION_PREVIOUS_KEYS} for one deploy, and the next boot moves everybody across. It is idempotent — a second boot finds nothing
     * to do — so the previous key can be removed whenever convenient.
     *
     * <p>
     * <strong>Cost.</strong> With no previous keys configured this reads a single row, because there is no rotation to perform and only the fit needs
     * proving. The full pass happens only during a rotation deploy, and touches one small row per account.
     *
     * @return what was rotated, and what no configured key could open
     */
    public KeyReconciliation reconcile() {
        final List<byte[]> retired = retiredKeys();
        if (retired.isEmpty()) {
            final UserNotesKey sample = UserNotesKey.findAny();
            final boolean fits = sample == null || DataKeyEnvelope.unwrap(sample.dekWrapped, masterKey(), sample.userId).isPresent();
            return fits ? KeyReconciliation.upToDate() : new KeyReconciliation(0, 1);
        }
        return rotateOnto(masterKey(), retired);
    }

    private static KeyReconciliation rotateOnto(final byte[] current, final List<byte[]> retired) {
        int rotated = 0;
        int unopenable = 0;

        for (final UserNotesKey stored : UserNotesKey.<UserNotesKey>listAll()) {
            if (DataKeyEnvelope.unwrap(stored.dekWrapped, current, stored.userId).isPresent()) {
                continue;
            }

            final Optional<byte[]> dataKey = openWithAnyOf(retired, stored);
            if (dataKey.isEmpty()) {
                unopenable++;
                continue;
            }

            // The data key itself is unchanged - only the wrapping around it - so not a single note is rewritten.
            stored.dekWrapped = DataKeyEnvelope.wrap(dataKey.get(), current, stored.userId);
            stored.keyVersion = (short) (stored.keyVersion + 1);
            stored.persist();
            rotated++;
        }
        return new KeyReconciliation(rotated, unopenable);
    }

    private static Optional<byte[]> openWithAnyOf(final List<byte[]> candidates, final UserNotesKey stored) {
        for (final byte[] candidate : candidates) {
            final Optional<byte[]> opened = DataKeyEnvelope.unwrap(stored.dekWrapped, candidate, stored.userId);
            if (opened.isPresent()) {
                return opened;
            }
        }
        return Optional.empty();
    }

    private List<byte[]> retiredKeys() {
        return notesEncryptionConfig.previousKeys()
            .orElseGet(List::of)
            .stream()
            .filter(key -> !key.isBlank())
            .map(MasterKey::decode)
            .toList();
    }

    private UserNotesKey mint(final UUID userId) {
        final UserNotesKey stored = new UserNotesKey();
        stored.userId = userId;
        stored.dekWrapped = DataKeyEnvelope.wrap(Aes256Gcm.randomKey(), masterKey(), userId);
        stored.persist();
        return stored;
    }

    private Optional<byte[]> open(final UserNotesKey stored) {
        final Optional<byte[]> dataKey = DataKeyEnvelope.unwrap(stored.dekWrapped, masterKey(), stored.userId);
        if (dataKey.isEmpty()) {
            // The account only - never the key, and never a note. See the class Javadoc.
            LOGGER.error("NOTE_ENCRYPTION_KEY does not open the notes data key for account {} - their notes cannot be read. "
                + "This is a configuration fault: the key differs from the one their data was written under.", emailOf(stored));
        }
        return dataKey;
    }

    private static String emailOf(final UserNotesKey stored) {
        return emailOf(stored.userId);
    }

    private static String emailOf(final UUID owner) {
        return User.<User>findByIdOptional(owner)
            .map(user -> user.email)
            .orElse("unknown");
    }

    // Decoded per call rather than cached. It used to run per NOTE, which mattered when the dashboard warmed three
    // months in one request; NoteService.readContents now resolves the key once for a whole range, so this is a
    // handful of base64 decodes per request and not worth a field whose publication needs reasoning about.
    private byte[] masterKey() {
        // orElse("") rather than orElseThrow: MasterKey owns every "unusable key" message, and an absent
        // key is one of them - startup has already refused to boot on it, so this is unreachable in practice.
        return MasterKey.decode(notesEncryptionConfig.key().orElse(""));
    }
}
