/*
 * BSD Zero Clause License
 *
 * Copyright (c) 2026-2026 zodac.net
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
 * SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
 * IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

package net.zodac.diurnal.note;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import net.zodac.diurnal.config.NotesEncryptionConfig;
import net.zodac.diurnal.crypto.Aes256Gcm;
import net.zodac.diurnal.crypto.DataKeyEnvelope;
import net.zodac.diurnal.crypto.MasterKey;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * The single owner of a user's notes data key: minting one when their account is created, and opening it on the requests that read or write a note.
 *
 * <p>
 * The key is generated by the application and never involves the user — it is not shown to them, cannot be chosen or changed by them, and nothing
 * about it appears in the interface. What protects it is {@code NOTE_ENCRYPTION_KEY}, which lives in configuration rather than in the database, so
 * the sealed notes and the wrapped keys are together useless to anyone holding only a dump, a backup or a replica.
 *
 * <p>
 * <strong>An administrator with the running server has both</strong>, and can therefore read notes. That is the deliberate limit of this design: it
 * defends against losing the database, not against the operator. Anything stronger requires the user to hold a secret, which was tried and removed.
 *
 * <p>
 * <strong>A data key must never reach the application log</strong>, on the same terms as a note's content itself (see {@link NoteService}) and more
 * strictly still — a leaked note exposes one day, a leaked data key exposes every day at once. Every statement here logs the account and no more.
 *
 * <p>
 * Callers own the transaction; the minting methods assume one is already active.
 */
@ApplicationScoped
public class NoteKeys {

    private static final Logger LOGGER = LogManager.getLogger(NoteKeys.class);

    private final NotesEncryptionConfig notesEncryptionConfig;

    /**
     * Injects the configured master key that every user's data key is wrapped with.
     *
     * @param notesEncryptionConfig the notes encryption settings
     */
    @Inject
    public NoteKeys(final NotesEncryptionConfig notesEncryptionConfig) {
        this.notesEncryptionConfig = notesEncryptionConfig;
    }

    /**
     * Mints a data key for a newly-created account and stores it wrapped.
     *
     * <p>
     * Called from every path that creates a user — local registration and OIDC provisioning alike — so an account has somewhere to put a note from
     * the moment it exists, and no part of the application ever has to handle the "user without a key" case as a live state.
     *
     * @param userId the account to mint a key for
     */
    public void assignTo(final UUID userId) {
        mint(userId);
    }

    /**
     * Opens the user's data key, or reports empty when there is none.
     *
     * <p>
     * An empty result means the account has no key, which is only possible for one created before this feature existed — and such an account has no
     * notes either, because writing one mints a key first. A key that exists but does not open is a different matter entirely: that is a mismatched
     * {@code NOTE_ENCRYPTION_KEY}, and it is logged at {@code error} rather than passed off as "no notes", because the alternative is a user's whole
     * journal disappearing from the interface with nothing said anywhere.
     *
     * @param userId the owning user
     * @return the data key, or empty when the account has none or it cannot be opened
     */
    Optional<byte[]> forUser(final UUID userId) {
        final UserNotesKey stored = UserNotesKey.findForUser(userId);
        return stored == null ? Optional.empty() : open(stored);
    }

    /**
     * Opens the user's data key, minting one first if the account has none. Used by the write path, which is transactional and must always end with a
     * key — an account created before this feature existed gets one the first time it writes a note.
     *
     * @param userId the owning user
     * @return the data key, or empty when an existing key cannot be opened
     */
    Optional<byte[]> forUserCreatingIfAbsent(final UUID userId) {
        final UserNotesKey existing = UserNotesKey.findForUser(userId);
        return open(existing == null ? mint(userId) : existing);
    }

    /**
     * Brings every stored data key onto the current master key, and reports what could not be brought.
     *
     * <p>
     * This does two jobs that are really one question — "does the configured key fit the data?" — and it is the check that turns this feature's worst
     * failure into a refusal to start. A rotated or mistyped {@code NOTE_ENCRYPTION_KEY} is still well-formed, so the format check passes; it then
     * opens nothing, and every note vanishes from every screen while the rows sit untouched. The calendar's day markers still show, because they are
     * computed from dates and never touch content, so a user would see markers saying they wrote something beside an empty box, with nothing logged.
     *
     * <p>
     * <strong>Rotation.</strong> When previous keys are configured, every row that no longer opens under the current key is opened with one of them,
     * re-wrapped under the current key and its {@code key_version} bumped. That is the whole rotation mechanism: set the new key, keep the old one in
     * {@code NOTE_ENCRYPTION_PREVIOUS_KEYS} for one deploy, and the next boot moves everybody across. It is idempotent — a second boot finds nothing
     * to do — so the previous key can be removed whenever convenient.
     *
     * <p>
     * <strong>Cost.</strong> With no previous keys configured this reads a single row, because there is no rotation to perform and only the fit needs
     * proving. The full pass happens only during a rotation deploy, and touches one small row per account.
     *
     * @return what was rotated, and what no configured key could open
     */
    public KeyReconciliation reconcile() {
        final List<byte[]> retired = retiredKeys();
        if (retired.isEmpty()) {
            final UserNotesKey sample = UserNotesKey.findAny();
            final boolean fits = sample == null || DataKeyEnvelope.unwrap(sample.dekWrapped, masterKey(), sample.userId).isPresent();
            return fits ? KeyReconciliation.upToDate() : new KeyReconciliation(0, 1);
        }
        return rotateOnto(masterKey(), retired);
    }

    private static KeyReconciliation rotateOnto(final byte[] current, final List<byte[]> retired) {
        int rotated = 0;
        int unopenable = 0;

        for (final UserNotesKey stored : UserNotesKey.<UserNotesKey>listAll()) {
            if (DataKeyEnvelope.unwrap(stored.dekWrapped, current, stored.userId).isPresent()) {
                continue;
            }

            final Optional<byte[]> dataKey = openWithAnyOf(retired, stored);
            if (dataKey.isEmpty()) {
                unopenable++;
                continue;
            }

            // The data key itself is unchanged - only the wrapping around it - so not a single note is rewritten.
            stored.dekWrapped = DataKeyEnvelope.wrap(dataKey.get(), current, stored.userId);
            stored.keyVersion = (short) (stored.keyVersion + 1);
            stored.persist();
            rotated++;
        }
        return new KeyReconciliation(rotated, unopenable);
    }

    private static Optional<byte[]> openWithAnyOf(final List<byte[]> candidates, final UserNotesKey stored) {
        for (final byte[] candidate : candidates) {
            final Optional<byte[]> opened = DataKeyEnvelope.unwrap(stored.dekWrapped, candidate, stored.userId);
            if (opened.isPresent()) {
                return opened;
            }
        }
        return Optional.empty();
    }

    private List<byte[]> retiredKeys() {
        return notesEncryptionConfig.previousKeys()
            .orElseGet(List::of)
            .stream()
            .filter(key -> !key.isBlank())
            .map(MasterKey::decode)
            .toList();
    }

    private UserNotesKey mint(final UUID userId) {
        final UserNotesKey stored = new UserNotesKey();
        stored.userId = userId;
        stored.dekWrapped = DataKeyEnvelope.wrap(Aes256Gcm.randomKey(), masterKey(), userId);
        stored.persist();
        return stored;
    }

    private Optional<byte[]> open(final UserNotesKey stored) {
        final Optional<byte[]> dataKey = DataKeyEnvelope.unwrap(stored.dekWrapped, masterKey(), stored.userId);
        if (dataKey.isEmpty()) {
            // The account id only - never the key, and never a note. See the class Javadoc.
            LOGGER.error("NOTE_ENCRYPTION_KEY does not open the notes data key for account {} - their notes cannot be read. "
                + "This is a configuration fault: the key differs from the one their data was written under.", stored.userId);
        }
        return dataKey;
    }

    // Decoded per call rather than cached. It used to run per NOTE, which mattered when the dashboard warmed three
    // months in one request; NoteService.readContents now resolves the key once for a whole range, so this is a
    // handful of base64 decodes per request and not worth a field whose publication needs reasoning about.
    private byte[] masterKey() {
        // orElse("") rather than orElseThrow: MasterKey owns every "unusable key" message, and an absent
        // key is one of them - startup has already refused to boot on it, so this is unreachable in practice.
        return MasterKey.decode(notesEncryptionConfig.key().orElse(""));
    }
}
