#!/usr/bin/env node
/* eslint-disable no-console -- CLI build script: progress output to the console is intended */
/**
 * Copies pinned third-party browser assets out of node_modules into the served static web root.
 *
 * WHY THIS EXISTS
 * ---------------
 * Front-end libraries the pages load directly (currently just htmx) are self-hosted rather than
 * pulled from a CDN — no third-party origin, no SRI worries, no render-blocking cross-origin fetch,
 * and it keeps the door open to a strict script-src CSP. Instead of committing the vendored file, we
 * declare each library as an exact-pinned devDependency in frontend/package.json and copy its shipped, already
 * minified dist file into resources at build time. This mirrors how the Tailwind CSS is compiled from
 * frontend/css into resources/css: the copied files are build artifacts (.gitignored), regenerated by
 * every Maven build (the POM's `vendor-assets` exec) and, in Docker, by the `css` stage.
 *
 * The single win of this indirection: because every library is a normal package.json devDependency,
 * .github/scripts/update_dependency_versions.sh bumps them automatically (its npm updater pins every
 * dependency to the latest exact version) — there is nothing library-specific to maintain in that
 * script.
 *
 * ADDING A LIBRARY
 * ----------------
 * 1. `npm install --save-dev --save-exact <package>` so it is pinned in frontend/package.json / package-lock.
 * 2. Add one entry to ASSETS below: the file to copy from within node_modules, and where it lands
 *    under the served web root. The <link>/<script> in the templates references it by that name
 *    (via AppInfo for the content-hashed production filename — see layout.html / AppInfo).
 * 3. If it needs a long-cache immutable filename in production, hash it in the Dockerfile alongside
 *    the CSS/JS renames and bake the name into an AppConfig `assets.*-file` mapping.
 */

'use strict'

const fs = require('node:fs')
const path = require('node:path')

const REPO_ROOT = path.resolve(__dirname, '..')
const NODE_MODULES = path.join(REPO_ROOT, 'frontend', 'node_modules')
const WEB_ROOT = path.join(REPO_ROOT, 'src', 'main', 'resources', 'META-INF', 'resources')

/**
 * The manifest of vendored assets. `from` is resolved inside node_modules; `to` inside the served
 * static web root. One line per file — this is the extension point when adding a new library.
 */
const ASSETS = [
    { from: 'htmx.org/dist/htmx.min.js', to: 'js/htmx.min.js' },
]

let copied = 0
for (const asset of ASSETS) {
    const src = path.join(NODE_MODULES, asset.from)
    const dest = path.join(WEB_ROOT, asset.to)

    if (!fs.existsSync(src)) {
        console.error(`  ❌ Missing ${asset.from} in node_modules — run \`npm install\` first`)
        process.exitCode = 1
        continue
    }

    fs.mkdirSync(path.dirname(dest), { recursive: true })
    fs.copyFileSync(src, dest)
    console.log(`  ✅ ${asset.from} → ${path.relative(REPO_ROOT, dest)}`)
    copied += 1
}

if (process.exitCode) {
    throw new Error('vendor-assets: one or more assets could not be copied')
}
console.log(`Vendored ${copied} asset(s).`)
